// @flow
import { connect } from 'react-redux';
import { compose, lifecycle } from 'recompose';

import ChooseGameView from './ChooseGameView';

const gameCategory = {
  mindGame: [
    {
      gameID: 'mind1',
      gameType: 'mindGame',
      brand: 'Citizen',
      level: 'Level 1',
      name: 'Mind Game',
      del: 3,
      loop: 3,
      power: 1,
      rememberTime: 2,
      answerTime: 2,
      badge: 'Gold',
      badgeColor: '#3cd39f',
    },
    {
      gameID: 'mind2',
      gameType: 'mindGame',
      brand: 'Citizen',
      level: 'Level 2',
      name: 'Mind Game',
      del: 5,
      loop: 5,
      power: 2,
      rememberTime: 2,
      answerTime: 2,
      badge: 'Gold',
      badgeColor: '#3cd39f',
    },
    {
      gameID: 'mind3',
      gameType: 'mindGame',
      brand: 'Citizen',
      level: 'Level 3',
      name: 'Mind Game',
      del: 7,
      loop: 5,
      power: 3,
      rememberTime: 2,
      answerTime: 4,
      badge: 'Gold',
      badgeColor: '#3cd39f',
    },
    {
      gameID: 'mind4',
      gameType: 'mindGame',
      brand: 'Citizen',
      level: 'Level 4',
      name: 'Mind Game',
      del: 3,
      loop: 3,
      power: 4,
      rememberTime: 2,
      answerTime: 2,
      badge: 'Gold',
      badgeColor: '#3cd39f',
    },
    {
      gameID: 'mind5',
      gameType: 'mindGame',
      brand: 'Citizen',
      level: 'Level 5',
      name: 'Mind Game',
      del: 5,
      loop: 5,
      power: 1,
      rememberTime: 2,
      answerTime: 2,
      badge: 'Gold',
      badgeColor: '#3cd39f',
    },
    {
      gameID: 'mind6',
      gameType: 'mindGame',
      brand: 'Citizen',
      level: 'Level 6',
      name: 'Mind Game',
      del: 7,
      loop: 5,
      power: 1,
      rememberTime: 2,
      answerTime: 4,
      badge: 'Gold',
      badgeColor: '#3cd39f',
    },
  ],
  mathGame: [
    {
      gameID: 'math1',
      gameType: 'mathGame',
      brand: 'Citizen',
      level: 'Simple Math Game',
      name: 'Math Game',
      power: 1,
      del: 1,
      loop: 10,
      rememberTime: 2,
      answerTime: 2,
      badge: 'Gold',
      badgeColor: '#3cd39f',
    },
    {
      gameID: 'Math2',
      gameType: 'mathGame',
      brand: 'Citizen',
      level: 'Medium Math Game',
      name: 'Math Game',
      power: 2,
      del: 2,
      loop: 10,
      rememberTime: 2,
      answerTime: 3,
      badge: 'Platinum',
      badgeColor: '#3cd39f',
    },
    {
      gameID: 'Math3',
      gameType: 'mathGame',
      brand: 'Citizen',
      level: 'Complex Math Game',
      name: 'Math Game',
      power: 3,
      del: 3,
      loop: 10,
      rememberTime: 2,
      answerTime: 4,
      badge: 'Dimond',
      badgeColor: '#3cd39f',
    },
    {
      gameID: 'math4',
      gameType: 'mathGame',
      brand: 'Citizen',
      level: 'Math Game for Genius',
      name: 'Math Game',
      power: 4,
      del: 4,
      loop: 10,
      rememberTime: 2,
      answerTime: 5,
      badge: 'Genius',
      badgeColor: '#3cd39f',
    },
  ],
};

export default compose(
  connect(state => ({
    isLoading: false,
    games: state.games,
    levels: gameCategory,
  })),
)(ChooseGameView);
