const state11 = {
  answerTime: 2,
  badge: 'Gold',
  badgeColor: '#3cd39f',
  brand: 'Citizen',
  del: 1,
  gameID: 'math1',
  gameState: {
    answerTime: 2,
    badge: 'Gold',
    badgeColor: '#3cd39f',
    brand: 'Citizen',
    del: 1,
    gameID: 'math1',
    gameType: 'mathGame',
    level: 'Simple Math Game',
    loop: 10,
    name: 'Math Game',
    power: 1,
    rememberTime: 2,
    subtitle: 'Level Desc',
    title: 'Level 1',
  },
  gameType: 'mathGame',
  loop: 10,
  power: 1,
  rememberTime: 2,
  results: {
    mathGame: {
      Math2: {
        score: 22,
        top: 222,
        name: 'Test Game',
        level: 'Level 0',
        lastScore: 20,
        progress: 20,
      },
      Math3: {
        score: 22,
        top: 222,
        name: 'Test Game',
        level: 'Level 0',
        lastScore: 20,
        progress: 20,
      },
      math1: {
        score: 22,
        top: 222,
        name: 'Test Game',
        level: 'Level 0',
        lastScore: 20,
        progress: 20,
      },
      math4: {
        score: 22,
        top: 222,
        name: 'Test Game',
        level: 'Level 0',
        lastScore: 20,
        progress: 20,
      },
    },
    mindGame: {
      mind1: {
        score: 22,
        top: 222,
        name: 'Test Game',
        level: 'Level 0',
        lastScore: 20,
        progress: 20,
      },
      mind2: {
        score: 22,
        top: 222,
        name: 'Test Game',
        level: 'Level 0',
        lastScore: 20,
        progress: 20,
      },
      mind3: {
        score: 22,
        top: 222,
        name: 'Test Game',
        level: 'Level 0',
        lastScore: 20,
        progress: 20,
      },
      mind6: {
        score: 22,
        top: 222,
        name: 'Test Game',
        level: 'Level 0',
        lastScore: 20,
        progress: 20,
      },
    },
  }, 
  subtitle: 'Math Game Desc',
  title: 'Simple Math Game',
};

const state1 = {
  answerTime: 2,
  badge: 'Gold',
  badgeColor: '#3cd39f',
  brand: 'Citizen',
  del: 1,
  gameID: 'math1',
  gameType: 'mathGame',
  isLoading: false,
  loop: 10,
  power: 1,
  questions: [
    {
      answer: [Object],
      desc: '',
      id: 1,
      options: [Array],
      question: 'What"s the division 6 ÷ 2 = ? ',
      ref: '',
    },
    {
      answer: [Object],
      desc: '',
      id: 2,
      options: [Array],
      question: 'What"s the division 28 ÷ 7 = ? ',
      ref: '',
    },
    {
      answer: [Object],
      desc: '',
      id: 3,
      options: [Array],
      question: 'What"s the division 6 ÷ 3 = ? ',
      ref: '',
    },
    {
      answer: [Object],
      desc: '',
      id: 4,
      options: [Array],
      question: 'What"s the sum 4 + 1 = ? ',
      ref: '',
    },
    {
      answer: [Object],
      desc: '',
      id: 5,
      options: [Array],
      question: 'What"s the subtraction 3 - 1 = ? ',
      ref: '',
    },
    {
      answer: [Object],
      desc: '',
      id: 6,
      options: [Array],
      question: 'What"s the division 5 ÷ 1 = ? ',
      ref: '',
    },
    {
      answer: [Object],
      desc: '',
      id: 7,
      options: [Array],
      question: 'What"s the subtraction 7 - 2 = ? ',
      ref: '',
    },
    {
      answer: [Object],
      desc: '',
      id: 8,
      options: [Array],
      question: 'What"s the division 6 ÷ 2 = ? ',
      ref: '',
    },
    {
      answer: [Object],
      desc: '',
      id: 9,
      options: [Array],
      question: 'What"s the division 32 ÷ 4 = ? ',
      ref: '',
    },
    {
      answer: [Object],
      desc: '',
      id: 10,
      options: [Array],
      question: 'What"s the subtraction 6 - 6 = ? ',
      ref: '',
    },
  ],
  remainingTime: 2,
  subtitle: 'Math Game Desc',
  title: 'Simple Math Game',
};
const answer = {
  '1': { key: '7azitq1', setAnswer: 1, status: false },
  '2': { key: 'ut1wuu2', setAnswer: 2, status: true },
  '3': { key: 'xdr41n0', setAnswer: 36, status: true },
  '5': { key: 'o3vv1j1', setAnswer: 13, status: false },
};
const answer22 = {
  answerTime: 2,
  badge: 'Gold',
  badgeColor: '#3cd39f',
  brand: 'Citizen',
  del: 1,
  gameID: 'math1',
  gameType: 'mathGame',
  isLoading: false,
  loop: 10,
  power: 1,
  questions: [
    {
      answer: [Object],
      desc: 'What"s the multiplication ',
      id: 1,
      options: [Array],
      question: '1 × 7 = ?',
      ref: '',
    },
    {
      answer: [Object],
      desc: 'What"s the multiplication ',
      id: 2,
      options: [Array],
      question: '1 × 1 = ?',
      ref: '',
    },
    {
      answer: [Object],
      desc: 'What"s the division ',
      id: 3,
      options: [Array],
      question: '6 ÷ 6 = ?',
      ref: '',
    },
    {
      answer: [Object],
      desc: 'What"s the subtraction ',
      id: 4,
      options: [Array],
      question: '7 - 5 = ?',
      ref: '',
    },
    {
      answer: [Object],
      desc: 'What"s the division ',
      id: 5,
      options: [Array],
      question: '5 ÷ 5 = ?',
      ref: '',
    },
    {
      answer: [Object],
      desc: 'What"s the multiplication ',
      id: 6,
      options: [Array],
      question: '2 × 4 = ?',
      ref: '',
    },
    {
      answer: [Object],
      desc: 'What"s the division ',
      id: 7,
      options: [Array],
      question: '9 ÷ 9 = ?',
      ref: '',
    },
    {
      answer: [Object],
      desc: 'What"s the sum ',
      id: 8,
      options: [Array],
      question: '6 + 8 = ?',
      ref: '',
    },
    {
      answer: [Object],
      desc: 'What"s the multiplication ',
      id: 9,
      options: [Array],
      question: '1 × 9 = ?',
      ref: '',
    },
    {
      answer: [Object],
      desc: 'What"s the sum ',
      id: 10,
      options: [Array],
      question: '3 + 2 = ?',
      ref: '',
    },
  ],
  remainingTime: 2,
  subtitle: 'Math Game Desc',
  title: 'Simple Math Game',
};
const q2 = [
  { anser: [8, 5], desc: '', id: 1, options: '', question: [5, 3, 2], ref: '' },
  { anser: [2, 3], desc: '', id: 2, options: '', question: [2, 0, 3], ref: '' },
  { anser: [9, 9], desc: '', id: 3, options: '', question: [4, 5, 4], ref: '' },
];
